name: Build and Deploy Testing
on:
  push:
    branches:
      - testing*

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master

      - name: Install Dependencies
        run: npm install

      - name: Install Ionic CLI
        run: sudo npm install -g @ionic/cli

      - name: Build Ionic
        run: ionic build --release

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v1.3.0
        with:
          args: deploy --only hosting:test
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: diklabu-2020
